name: R

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up libraries for Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y libsodium-dev libharfbuzz-dev libfribidi-dev libcurl4-openssl-dev texlive-latex-base pandoc
      - name: Set up R 4.0
        uses: r-lib/actions/setup-r@master
        with:
          r-version: 4.0
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}/*
          key: ${{ runner.os }}-deps
      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          install.packages(c("remotes", "rcmdcheck", "BiocManager"))
          BiocManager::install(c("SummarizedExperiment", "SingleCellExperiment", "SpatialExperiment"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(error_on = "error")
        shell: Rscript {0}
        env:
          _R_CHECK_FORCE_SUGGESTS_: false
      - name: Build docs
        run: |
          Rscript -e 'pkgdown::build_site(new_process = FALSE)'
          touch docs/.nojekyll
      - name: Deploy docs to gh-pages branch
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
          site-directory: docs
